
name: ZFBrasil
description: Brazilian Zend Framework community

avatar: https://avatars2.githubusercontent.com/u/3143718

footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: zfbrasil
  instagram: 
  linkedin: 
  pinterest: 
  rss:
  twitter:
  stackoverflow:

disqus:
google_analytics:
url: http://zfbrasil.github.io

baseurl: ""

markdown: kramdown
highlighter: pygments
permalink: /:title/

version: v1.0.0

sass:
  sass_dir: _scss
  style: :expanded

gems:
  - jemoji
  - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
